variables:
  INSTANCE: sso-$CI_COMMIT_REF_SLUG
  VERSION: $CI_COMMIT_BRANCH

include:
  - project: fairdata/fairdata-ci
    ref: staging
    file:
      - /templates/deploy.yml
      - /templates/review.yml

stages:
  - deploy
  - test
  - clean

run_integration_tests:
  stage: test
  environment:
    name: $CI_COMMIT_BRANCH
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY $TEST_PLAYBOOK
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "test"'
#    - if: '$CI_COMMIT_BRANCH == "stable"'
#    - if: '$CI_COMMIT_BRANCH == "demo"'
#    - if: '$CI_COMMIT_BRANCH == "staging"'

sonarqube-check:
  tags:
    - docker
  stage: test
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true
  only:
    - merge_requests
    - master
    - test
    - staging
    - stable
    - demo
