variables:
  INSTANCE: sso-$CI_COMMIT_REF_SLUG
  VERSION: $CI_COMMIT_BRANCH

include:
  - project: fairdata/fairdata-ci
    ref: staging
    file:
      - /templates/deploy.yml
      - /templates/review.yml

stages:
  - deploy
  - test
  - clean

run_integration_tests:
  stage: test
  environment:
    name: $CI_COMMIT_BRANCH
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY $TEST_PLAYBOOK
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
    - if: '$CI_COMMIT_BRANCH == "stable"'
    - if: '$CI_COMMIT_BRANCH == "demo"'
    - if: '$CI_COMMIT_BRANCH == "staging"'
