variables:
  GITLAB_ENV: test
  SERVICE: ${SERVICE}

default:
  tags:
    - shell

stages:
  - test
  - deploy
  - e2e-test
  - integration-test

# --------

include:
  - project: fairdata/fairdata-ci
    ref: master
    file:
      - /templates/deploy/deploy.yml
      - /templates/test/sonarqube.yml
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^(master)$/
      - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

# --------

fairdata-e2e:
  stage: e2e-test
  trigger: fairdata/fairdata-ci
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

# --------

run-integration-tests:
  stage: integration-test
  environment: ${GITLAB_ENV}
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY $TEST_PLAYBOOK --vault-id $ANSIBLE_VAULT_FILE
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/
    - if: $CI_COMMIT_BRANCH !~ /^(master)$/ && $CI_PIPELINE_SOURCE =~ /^(web)$/
