version: '3.8'

services:
  sso-server:
    image: fairdata-docker.artifactory.ci.csc.fi/fairdata-sso
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_DEBUG: true
    volumes:
      - .:/app
    configs:
      - source: sso-server-config
        target: /etc/fairdata-sso/config.json
      - source: sso-saml-config
        target: /etc/fairdata-sso/saml.json

  fairdata-nginx:
    image: nginx
    configs:
      - source: fairdata-nginx-config
        target: /etc/nginx/nginx.conf
      - source: fairdata-ssl-certificate
        target: /etc/pki/tls/certs/ssl.crt.pem
      - source: fairdata-ssl-certificate-key
        target: /etc/pki/tls/private/ssl.key.pem
      - source: sso-nginx-config
        target: /etc/nginx/sites-enabled/sso
    ports:
      - 443:443

configs:
  sso-server-config:
    external: true
  sso-saml-config:
    external: true
  sso-nginx-config:
    external: true

  fairdata-nginx-config:
    external: true
  fairdata-ssl-certificate:
    external: true
  fairdata-ssl-certificate-key:
    external: true
