#!/usr/bin/env bash

PYTHON="/opt/fairdata/python3/bin/python"

ID=`id -u -n`
if [ "$ID" != "root" ]; then
    echo "You must execute this script as root" >&2
    exit 1
fi

if [ ! -x $PYTHON ]; then
    echo "$PYTHON does not exist!" >&2
    exit 1
fi

SCRIPT="$(realpath $0)"
UTILS=`dirname "$SCRIPT"`
ROOT=`dirname "$UTILS"`

rm -fr $ROOT/venv 2>/dev/null

$PYTHON -m venv $ROOT/venv

source $ROOT/venv/bin/activate

pip install --upgrade pip
pip install 'wheel>=0.34.2' --force-reinstall
pip install -r $ROOT/requirements.txt

