#!/usr/bin/env bash

SCRIPT="$(realpath $0)"
UTILS=`dirname "$SCRIPT"`
ROOT=`dirname "$UTILS"`

$UTILS/initialize-venv

if [ ! -d /var/log/fairdata-sso ]; then
    mkdir -p /var/log/fairdata-sso
fi

ln -s $ROOT/fairdata-sso.service /usr/lib/systemd/system/fairdata-sso.service

systemctl daemon-reload
systemctl enable fairdata-sso
systemctl start fairdata-sso
systemctl status fairdata-sso
