#!/usr/bin/env bash

PYTHON="/opt/fairdata/python3/bin/python3.8"

ID=`id -u -n`
if [ "$ID" != "root" ]; then
    echo "You must execute this script as root" >&2
    exit 1
fi

if [ ! -x $PYTHON ]; then
    echo "$PYTHON does not exist!" >&2
    exit 1
fi

SCRIPT="$(realpath $0)"
UTILS=`dirname "$SCRIPT"`
ROOT=`dirname "$UTILS"`

if [ ! -d $ROOT/venv ]; then
    echo "Could not find virtual environment!" >&2
    exit 1
fi

source $ROOT/venv/bin/activate

pip install --upgrade pip
pip install -r $ROOT/requirements.txt

