#!/usr/bin/env bash

SCRIPT="$(realpath $0)"
LDAPDIR=`dirname "$SCRIPT"`
ROOT=`dirname "$LDAPDIR"`

# Parameters can be provided either as command line arguments or via pre-defined environment variables
# LDAP_PROJECT: A project number or name

if [ "$1" ]; then
    LDAP_PROJECT="$1"
fi

if [ -z "$LDAP_PROJECT" ]; then
    echo "Missing required parameter LDAP_PROJECT" >&2
    exit 1
fi

export LDAP_PROJECT
export ROOT

source $ROOT/venv/bin/activate

python $LDAPDIR/retrieve_project_details.py
